### ISSUE TITLE
Can this node cast to groups?

### ISSUE THREAD

**Issue by GrahamP-P** [Hypnos3/node-red-contrib-cast#20]
Thank you for this node.

Can it be configured to talk to devices groups?

Within then Google Home App I have created a group called "All Speakers" that contains all my chromecast audios, google home and Minis. I'd like to be able to send to the group from the node. Is that currently possible, if not can it be added please?

**Comment by Hypnos3** [comment]
The node sends the data directly to a device without involving google server.
Immediately I would not know how to go and therefore I would have to test here. Since I only have one device, unfortunately I can not test anything there.

**Comment by GrahamP-P** [comment]
If you can tell me how to test I'd gladly assist, as I have multiple devices in groups.

**Comment by Hypnos3** [comment]
OK, I must implement the [device scanner](https://github.com/thibauts/node-castv2-client/wiki/How-to-discover-&-update-audio-groups), but this will take a while (>2 weeks).
I will let you know when this is ready.

**Comment by AndrewBarfield** [comment]
Thank you for working on this. If I can help somehow, please let me know.

**Comment by Hypnos3** [comment]
Unfortunately, due to lack of time, I am currently unable to do so. Therefore, it will take some time.

**Comment by arachnida** [comment]
Not exactly the same as what GrahamP-P wanted but similar, could you implement the broadcast function?

**Comment by Martin-Dolan** [comment]
Yes, Broadcast or send to a group would be great as I want it to announce things throughout the house on the google home devices without killing the music playing on the chromecast audio.
If tell it to output to a bunch of google home devices via their IP address they will all play out of sync

Intended use is to announce someone at the door etc. (doorbell that can be heard throughout the house)

**Comment by whoamicz** [comment]
This node is best (without bugs), but I used different one before, after scanning my google home devices i found on one of them one more opened port and when i streamed to this port it played on speaker group, this node will fail when streaming to this port.

**Comment by Hypnos3** [comment]
What is the different port?

**Comment by Hypnos3** [comment]
With Version 0.2.6 it is possible to cast to groups. You need to select Port of the Group.

**Comment by djsheetu** [comment]
First of all congratulations for getting this resolved.

Can i please request you to point me in the direction how I can find the "different port" of the home group?

Thanks

**Comment by Hypnos3** [comment]
I was told that you can address the group by choosing a different port. There is now the selection of the ports in the configuration.

Since I have only one Google Home Mini, I can not test it myself and therefore I can not describe it more accurately. I have not received any donations, so I can not buy any more.

**Comment by djsheetu** [comment]
Thanks for the reply. But AFAIK there is no way to find out port number in the google home app. There should be a way to "scan" the ports some how. Thanks for your efforts.

I will keep looking...

**Comment by djsheetu** [comment]
> This node is best (without bugs), but I used different one before, after scanning my google home devices i found on one of them one more opened port and when i streamed to this port it played on speaker group, this node will fail when streaming to this port.

Could you please advise how you "scanned" the google home devices?

**Comment by Hypnos3** [comment]
Does the Button in the settings of the node not working?
![image](https://user-images.githubusercontent.com/12692680/55384940-4ff6b100-552c-11e9-9890-c3545d22a762.png)

**Comment by Hypnos3** [comment]
@tomas-bara The Bug with selecting different Port is fixed in the meantime.

**Comment by djsheetu** [comment]
You are the MAN!!!

I wasn't reading (understanding) the process correctly and was assuming i have to scan for open ports by using some other "program" instead of clicking the "search button". I was using my Router to find the IP of my google homes...

Thanks heaps for being patient and pointing this out and guiding me through.

I have 5 Goggle Homes and one chromecast audio and have created 3 different groups. Once I clicked There were some 125-130 entries in the drop down box with a lot of them repeating the same IP and ports.  Most of them spit out an error ""Client error reported:connect ECONNREFUSED XX.XX.XX.XX:PortNo".

Took me a while to find the ones that actually works. I believe "IP and port no combo" using the the IP of the google home/chromecast which was added first while creating the "cast group" works.

Thanks again for your efforts and I can confirm casting to the groups works.

**Comment by tomas-bara** [comment]
@Hypnos3 I'm so sorry, i missed notifications, I actually used nmap (https://nmap.org/) to scan my master google home device for opened ports and I tried all of them (just few ports) until I mapped what port is used for what group.

Thank you for port selection fix. :-)

**Comment by marc-gist** [comment]
@tomas-bara what ports did they end up being on? none of the 5 ports that show up i nmap work (except the 8009 of course)... all my devices show the same ports.

**Comment by RichardUUU** [comment]
I have a group with three home minis. Using the search button next to IP for this node I get an IP for one of the three minis with a port in the 40000 area. Casting to that only goes to the mini for that IP address.

**Comment by MostHated** [comment]
Just in case anyone comes across this in the future, as I did, this tool called NetBrowse helped me find my cast group info extremely easily.

https://github.com/Ewpratten/netbrowse

![](https://i.imgur.com/WhLvl2A.png)
