### ISSUE TITLE
Add possibility to set volume back to before cast

### ISSUE THREAD

**Issue by MTrab** [Hypnos3/node-red-contrib-cast#34]
When changing volume, for example when doing a TTS cast to Google Home devices, it sometime scould be a neat feature to have the cast node set the volume back to the level from before.

**Comment by Twanislas** [comment]
Hi !

I use a trigger node for this. Hope this helps :)

![image](https://user-images.githubusercontent.com/524706/52371215-361d7e00-2a55-11e9-90e3-3df1be888b59.png)

**Comment by MTrab** [comment]
> Hi !
> 
> I use a trigger node for this. Hope this helps :)
> 
> ![image](https://user-images.githubusercontent.com/524706/52371215-361d7e00-2a55-11e9-90e3-3df1be888b59.png)

But what if the volume was 30%? Or 60%? Or 10%?
The volume aren't static at this house *LOL*

**Comment by Hypnos3** [comment]
You can simply save the old volume in a context and restore them with the trigger node.

**Comment by MTrab** [comment]
Yes, but you need a pretty hefty flow to get the volume in the first place.

**Comment by Hypnos3** [comment]
Implementing this in in the node will also may be "hefty".

The cast node needs to know when the file/stream is ending (tts is converted to a mp3 file) to be able to reset the volume. To thus they can get the state of the cast device by polling to see if it is already playing or the length must be given with the input or ??.

I will think about it.

**Comment by Diez66** [comment]
Hi, using this and although I am having some problems, due to a lack of ability on my part, I am still learning. What I needed working; works. Thanks.

I also think a reset volume to previous would be good, so if you ever do, brilliant. 

In the meantime I will make a bodge to my flow and set the volume to lower than MAX, which is what I had set it to without any thought to afterwards. Not the best feedback form the family, my bad.

**Comment by Diez66** [comment]
Hi, using this and although I am having some problems, due to a lack of ability on my part, I am still learning. What I needed working; works. Thanks.

I also think a reset volume to previous would be good, so if you ever do, brilliant.

In the meantime I will make a bodge to my flow and set the volume to lower than MAX, which is what I had set it to without any thought to afterwards. Not the best feedback from my family about what I have implemented volume wise, this is my bad. 
Your Node-Red node is super.

**Comment by Hypnos3** [comment]
still in plan

**Comment by Diez66** [comment]
I am glad this is still in plan as it will be very useful, my bodge of just setting it low by sending another message is OK and sometimes funny as I have a random selection of supply outbursts. This will be better.

**Comment by ChrisJohns-me** [comment]
https://github.com/orcema/node-red-contrib-google-home-notifier-offline has this implemented. It restores the Google Home volume after casting a TTS notification.
