### ISSUE TITLE
unable to stop media

### ISSUE THREAD

**Issue by eh03** [Hypnos3/node-red-contrib-cast#47]
iam unable to stop the media.
i sent no message and no url to my google home, but the playing sound doesn't stop.

**Comment by i8beef** [comment]
Likely broken by your fix for #16

**Comment by domi-a** [comment]
is this essential payback bug going to be fixed? 6 months is a pretty long time for an "important" bug

**Comment by Hypnos3** [comment]
Thanks, the "important" label was wrong.  The node has little priority, so that the development is very slow.
But PR's are welcome!

**Comment by i8beef** [comment]
I did try to fix it but never was able to do it without breaking other things. I was kinda in a bind so I wrote my own simplified version. Not trying to promote it here (feel free to hide this comment if its unwelcome), but if you find yourself in a similar bind, it IS public...

**Comment by domi-a** [comment]
so after 2 years for me this bug is still important and essential functions of the package.
i just upgraded to the 2.17 and was curious to see if there is a fix.
but there is not.

just testet out the other package [https://flows.nodered.org/node/node-red-contrib-castv2](https://flows.nodered.org/node/node-red-contrib-castv2)
little other to use but does the job and is able to stop gracefully.
seems to be related to this updated package. maintainer writing some lines above ;-)
