### ISSUE TITLE
url list

### ISSUE THREAD

**Issue by LeeJoeIng** [Hypnos3/node-red-contrib-cast#63]
Hi there! 
I've tested the url list feature by giving an array of urls of image. However, it is always the second image being casted. Is that a problem of duration or something else ? What should I do in order to cast the image in order with a good timing ? 

Thanks.

**Comment by haaslukas** [comment]
Same here. The urlList feature always seems to skip the first mp3. I've just added a dummy string as first array item in order to play my full list.

And I've noticed something else: The first 2-3 seconds of all mp3 files in the list are cut off (except of the first file in the list that get played). Could that be a google home mini buffering issue?

**Comment by Hypnos3** [comment]
still in work

**Comment by jparthum** [comment]
I think the problem is on line 530 of cast-to-client.js:

`startIndex: 1,`

should be

`startIndex: 0,`

**Comment by Hypnos3** [comment]
@jparthum Thank you for your hint. I have changed this and published a new version.
