### ISSUE TITLE
SSML - Is it possible to use SSML markup for google TTS ?

### ISSUE THREAD

**Issue by ozett** [Hypnos3/node-red-contrib-cast#75]
i tried to put
```
 <say-as interpret-as=\"characters\">SSML</say-as>
```
into the payload, but it was not used as Markup.

is it possible somehow to use SSML tags?

more to SSML on google tts --> https://cloud.google.com/text-to-speech/docs/ssml

**Comment by Hypnos3** [comment]
This depends if it will be implemented in the used [library ](https://github.com/zlargon/google-tts).

But I do not think this makes sense with the current approach. The google-tts implementation uses the API of Google translate and not of Google [Cloud Text-to-Speech](https://cloud.google.com/text-to-speech/). The reason is that the Google translate API can be used for free, whereas to my knowledge [Cloud Text-to-Speech](https://cloud.google.com/text-to-speech/) is chargeable.

I'll close this issue for now, because it needs competition of this [issue](https://github.com/zlargon/google-tts/issues/29) first. If this has been implemented in the library or if an alternative library exists, you are welcome to reopen this issue.

**Comment by ozett** [comment]
sorry for this addition. i dont want to open this again, but i thought maybe it is here of interest, that there could be a node-red implementation for the cloud-text-to-speech.

it seems that momentarily some limit amount of tts is still free..

https://www.npmjs.com/package/@google-cloud/text-to-speech

(thx for detailed an serious answer..can still stay ... closed.. 😉 )
