### ISSUE TITLE
outcome node

### ISSUE THREAD

**Issue by pvklink** [Hypnos3/node-red-contrib-cast#80]
Hi, i use your node for streaming webcams and it works great. Thank you for that!

I only had one issue. The original msg ID (_msgid) is not passed through. So i cant merge this node output with other splitted messages . When a node dont passes al previous info and dont pass the original ID it is hard to keep parts of flows together and keep flow information complete

See: https://nodered.org/docs/creating-nodes/
Nodes should document what properties they ADD to messages, and they should be consistent and predictable in their behaviour.

**Comment by Hypnos3** [comment]
Currently it creates a new output messages.

The incomming message triggers the chromecast to play the given media and no output will be send.

The outgoing message is created independend of this every time when the chromecase send a state message. This can, but does not have to be due to the incoming command. In any case, it is independent of time and the chromecast device decides when this is so.

Logically the outgoing message has nothing to do with the incomming message and to thus this is a separate message with a separate messageID.

I could technically remember the last incoming message and send all outgoing with this message ID. But i don't know if this is a good idea because it can send multiple messages with the same id that have nothing to do with each other.

**Comment by Hypnos3** [comment]
Currently it creates a new output messages.

The incomming message triggers the chromecast to play the given media and no output will be send.

The outgoing message is created independend of this every time when the chromecase send a state message. This can, but does not have to be due to the incoming command. In any case, it is independent of time and the chromecast device decides when this is so.

Logically the outgoing message has nothing to do with the incomming message and to thus this is a separate message with a separate messageID.

I could technically remember the last incoming message and send all outgoing with this message ID. But i don't know if this is a good idea because it can send multiple messages with the same id that have nothing to do with each other.

**Comment by Hypnos3** [comment]
I use the standard function to send and forward the incoming message without changing the message ID.

**Comment by Hypnos3** [comment]
OK, I can not reproduce your problem:
![image](https://user-images.githubusercontent.com/12692680/74478679-288fa500-4eae-11ea-9f6e-6c244ef95f4a.png)

As you can see has the incoming message the same ID as the outgoing message.

There are additional messages in the meantime, which are state messages from the case device. These send Independent to the incoming message at every state change of the cast device. This can, but must not be have anything to do with the incoming message.

**Comment by pvklink** [comment]
You are right!
I updated my nodes and it works!

I used castv2 and i changed to your version.
I castv2 there is an option to reset the Nest hub with
Is that possible with this cast version too?

msg = 
    {
    host: msg.ip_nest,
    mstatus: "NEST closed...einde",
    payload:    {
                type: "CLOSE",
                }
    };

return msg;

**Comment by Hypnos3** [comment]
currently not, I will see if I could also implement it.

**Comment by pvklink** [comment]
the problem with the beep every refresh is solved my turning the volume to 0 in the msg
